ABBREVIATIONS = {
    'ALLPURP': 'All Purpose',
    'AL': 'Aluminum',
    '&amp;': 'And',
    'APPL': 'Apple',
    'APPLS': 'Apples',
    'APPLSAUC': 'Applesauce',
    'APPROX': 'Approximately',
    'ARM&amp;BLD': 'Arm and Blade',
    'ART': 'Artificial',
    'VIT C': 'Vitamin C',
    'ASPRT': 'Aspartame',
    'ASPRT-SWTND': 'Aspartame-sweetened',
    'BABYFD': 'Babyfood',
    'BKD': 'Baked',
    'BBQ': 'Barbequed',
    'BSD': 'Based',
    'BNS': 'Beans',
    'BF': 'Beef',
    'BEV': 'Beverage',
    'BLD': 'Boiled',
    'BNLESS': 'Boneless',
    'BTLD': 'Bottled',
    'BTTM': 'Bottom',
    'BRSD': 'Braised',
    'BRKFST': 'Breakfast',
    'BRLD': 'Broiled',
    'BTTRMLK': 'Buttermilk',
    'CA': 'Calcium',
    'CAL': 'Calorie, calories',
    'CND': 'Canned',
    'CARB': 'Carbonated',
    'CNTR': 'Center',
    'CRL': 'Cereal',
    'CHS': 'Cheese',
    'CHICK': 'Chicken',
    'CHOC': 'Chocolate',
    'CHOIC': 'Choice',
    'CHOL': 'Cholesterol',
    'CHOL-FREE': 'Cholesterol-free',
    'CHOPD': 'Chopped',
    'CINN': 'Cinnamon',
    'COATD': 'Coated',
    'COCNT': 'Coconut',
    'COMM': 'Commercial',
    'COMMLY': 'Commercially',
    'CMDTY': 'Commodity',
    'COMP': 'Composite',
    'CONC': 'Concentrate',
    'CONCD': 'Concentrated',
    'COND': 'Condensed',
    'CONDMNT': 'Condiment, condiments',
    'CKD': 'Cooked',
    'CTTNSD': 'Cottonseed',
    'CRM': 'Cream',
    'CRMD': 'Creamed',
    'DK': 'Dark',
    'DECORT': 'Decorticated',
    'DEHYD': 'Dehydrated',
    'DSSRT': 'Dessert, desserts',
    'DIL': 'Diluted',
    'DOM': 'Domestic',
    'DRND': 'Drained',
    'DRSNG': 'Dressing',
    'DRK': 'Drink',
    'DRUMSTK': 'Drumstick',
    'ENG': 'English',
    'ENR': 'Enriched',
    'EQ': 'Equal',
    'EVAP': 'Evaporated',
    'XCPT': 'Except',
    'EX': 'Extra',
    'FLANKSTK': 'Flank steak',
    'FLAV': 'Flavored',
    'FLR': 'Flour',
    'FD': 'Food',
    'FORT': 'Fortified',
    'FRENCH FR': 'French fries',
    'FRSH': 'Fresh',
    'FRSTD': 'Frosted',
    'FRSTNG': 'Frosting',
    'FRZ': 'Frozen',
    'GRDS': 'Grades',
    'GM': 'Gram',
    'GRN': 'Green',
    'GRNS': 'Greens',
    'HTD': 'Heated',
    'HVY': 'Heavy',
    'HI-MT': 'Hi-meat',
    'HI': 'High',
    'HR': 'Hour',
    'HYDR': 'Hydrogenated',
    'IMITN': 'Imitation',
    'IMMAT': 'Immature',
    'IMP': 'Imported',
    'INCL': 'Including',
    'INF FORMULA': 'Infant formula',
    'ING': 'Ingredient',
    'INST': 'Instant',
    'JUC': 'Juice',
    'JR': 'Junior',
    'KRNLS': 'Kernels',
    'LRG': 'Large',
    'LN': 'Lean only',
    'LVND': 'Leavened',
    'LT': 'Light',
    'LIQ': 'Liquid',
    'LO': 'Low',
    'LOFAT': 'Low Fat',
    'MARSHMLLW': 'Marshmallow',
    'MSHD': 'Mashed',
    'MAYO': 'Mayonnaise',
    'MED': 'Medium',
    'MESQ': 'Mesquite',
    'MIN': 'Minutes',
    'MXD': 'Mixed',
    'MOIST': 'Moisture',
    'NAT': 'Natural',
    'NZ': 'New Zealand',
    'NFDM': 'Nonfat Dry Milk',
    'NFDMS': 'Nonfat Dry Milk Solids',
    'NFMS': 'Nonfat Milk Solids',
    'NONCARB': 'Noncarbonated',
    'NFS': 'Not Further Specified',
    'NUTR': 'Nutrition',
    'OZ': 'Ounce',
    'PK': 'Pack',
    'PAR FR': 'Partially fried',
    'PARBLD': 'Parboiled',
    'PART': 'Partially',
    'PAST': 'Pasteurized',
    'PNUT': 'Peanut',
    'PNUTS': 'Peanuts',
    'PO4': 'Phosphate',
    'P': 'Phosphorus',
    'PNAPPL': 'Pineapple',
    'PLN': 'Plain',
    'PRTRHS': 'Porterhouse',
    'K': 'Potassium',
    'PDR': 'Powdered',
    'PRECKD': 'Precooked',
    'PREHTD': 'Preheated',
    'PREP': 'Prepared',
    'PROC': 'Processed',
    'PROD CD': 'Product code',
    'PROP': 'Propionate',
    'PROT': 'Protein',
    'PUDD': 'Pudding, puddings',
    'RTB': 'Ready-to-bake',
    'RTC': 'Ready-to-cook',
    'RTD': 'Ready-to-drink',
    'RTE': 'Ready-to-eat',
    'RTF': 'Ready-to-feed',
    'RTH': 'Ready-to-heat',
    'RTS': 'Ready-to-serve',
    'RTU': 'Ready-to-use',
    'RECON': 'Reconstituted',
    'RED': 'Reduced',
    'RED-CAL': 'Reduced-calorie',
    'REFR': 'Refrigerated',
    'REG': 'Regular',
    'REHTD': 'Reheated',
    'REPLCMNT': 'Replacement',
    'REST-PREP': 'Restaurant-prepared',
    'RTL': 'Retail',
    'RST': 'Roast',
    'RSTD': 'Roasted',
    'RND': 'Round',
    'SNDWCH': 'Sandwich',
    'SAU': 'Sauce',
    'SCALLPD': 'Scalloped',
    'SCRMBLD': 'Scrambled',
    'SD': 'Seed',
    'SEL': 'Select',
    'SHK&amp;SIRL': 'Shank and sirloin',
    'SHRT': 'Short',
    'SHLDR': 'Shoulder',
    'SIMMRD': 'Simmered',
    'SKN': 'Skin',
    'SML': 'Small',
    'NA': 'Sodium',
    'SOL': 'Solids',
    'SOLN': 'Solution',
    'SOYBN': 'Soybean',
    'SPL': 'Special',
    'SP': 'Species',
    'SPRD': 'Spread',
    'STD': 'Standard',
    'STMD': 'Steamed',
    'STWD': 'Stewed',
    'STK': 'Stick',
    'STKS': 'Sticks',
    'STR': 'Strained',
    'SUB': 'Substitute',
    'SMMR': 'Summer',
    'SUPP': 'Supplement',
    'SWT': 'Sweet',
    'SWTND': 'Sweetened',
    'SWTNR': 'Sweetener',
    'TSP': 'Teaspoon',
    '1000': 'Thousand',
    'TSTD': 'Toasted',
    'TODD': 'Toddler',
    'UNCKD': 'Uncooked',
    'UNCRMD': 'Uncreamed',
    'UNDIL': 'Undiluted',
    'UNENR': 'Unenriched',
    'UNHTD': 'Unheated',
    'UNPREP': 'Unprepared',
    'UNSPEC': 'Unspecified',
    'UNSWTND': 'Unsweetened',
    'VAR': 'Variety, varieties',
    'VEG': 'Vegetable, vegetables',
    'VIT A': 'Vitamin A',
    'H20': 'Water',
    'WHTNR': 'Whitener',
    'WHL': 'Whole',
    'WNTR': 'Winter',
    'W/': 'With',
    'WO/': 'Without',
    'YEL': 'Yellow'
}
