# Generated by Django 2.2.1 on 2019-06-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_household_weight', models.FloatField(default=0.0)),
                ('first_household_weight_description', models.CharField(max_length=200)),
                ('second_household_weight', models.FloatField(default=0.0)),
                ('second_household_weight_description', models.CharField(max_length=200)),
                ('alpha_carotene', models.FloatField(default=0.0)),
                ('ash', models.FloatField(default=0.0)),
                ('beta_carotene', models.FloatField(default=0.0)),
                ('beta_cryptoxanthin', models.FloatField(default=0.0)),
                ('calcium', models.FloatField(default=0.0)),
                ('carbohydrate', models.FloatField(default=0.0)),
                ('category', models.CharField(max_length=200)),
                ('cholesterol', models.FloatField(default=0.0)),
                ('choline', models.FloatField(default=0.0)),
                ('copper', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=200)),
                ('fiber', models.FloatField(default=0.0)),
                ('iron', models.FloatField(default=0.0)),
                ('kilocalories', models.FloatField(default=0.0)),
                ('lutein_and_zeaxanthin', models.FloatField(default=0.0)),
                ('lycopene', models.FloatField(default=0.0)),
                ('magnesium', models.FloatField(default=0.0)),
                ('manganese', models.FloatField(default=0.0)),
                ('monosaturated_fat', models.FloatField(default=0.0)),
                ('niacin', models.FloatField(default=0.0)),
                ('nutrient_data_bank_number', models.IntegerField()),
                ('pantothenic_acid', models.FloatField(default=0.0)),
                ('phosphorus', models.FloatField(default=0.0)),
                ('polysaturated_fat', models.FloatField(default=0.0)),
                ('potassium', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('refuse_percentage', models.FloatField(default=0.0)),
                ('retinol', models.FloatField(default=0.0)),
                ('riboflavin', models.FloatField(default=0.0)),
                ('saturated_fat', models.FloatField(default=0.0)),
                ('selenium', models.FloatField(default=0.0)),
                ('sodium', models.FloatField(default=0.0)),
                ('sugar_total', models.FloatField(default=0.0)),
                ('thiamin', models.FloatField(default=0.0)),
                ('total_lipid', models.FloatField(default=0.0)),
                ('vitamin_a_iu', models.FloatField(default=0.0)),
                ('vitamin_a_rae', models.FloatField(default=0.0)),
                ('vitamin_b12', models.FloatField(default=0.0)),
                ('vitamin_b6', models.FloatField(default=0.0)),
                ('vitamin_c', models.FloatField(default=0.0)),
                ('vitamin_e', models.FloatField(default=0.0)),
                ('vitamin_k', models.FloatField(default=0.0)),
                ('water', models.FloatField(default=0.0)),
                ('zinc', models.FloatField(default=0.0)),
                ('density', models.FloatField(default=0.0)),
            ],
        ),
    ]
